### ISSUE TITLE
Save only year for animal birthDate

### ISSUE THREAD

**Issue by ignasposka** [pets-oss/pets-back#107]

**Comment by AzisK** [comment]
Why do we want to save only year?

**Comment by ignasposka** [comment]
> Why do we want to save only year?

Because animal shelters rarely know exact birthdate and it's not that relevant.

**Comment by AzisK** [comment]
I personally believe it's relevant. If nobody knows the exact month and day, we can default to 1st month and 1st day

**Comment by ignasposka** [comment]
Well, this was decided with project owner (Lina). I think it's messy to have major part of data just defaulted...

**Comment by ignasposka** [comment]
Closed because after additional discussion with PO it was decided to leave birthdate functionality as it is.
