### ISSUE TITLE
Add mutation for given away event

### ISSUE THREAD

**Issue by ignasposka** [pets-oss/pets-back#113]
**Goal**

* Create a GraphQL mutation `createGivenAwayEvent` that would create found event data in the database.
* Create a GraphQL mutation `updateGivenAwayEvent` that would update found event data in the database by specific ID.

**Description**

* Given away events are being stored in `animal_event_given_away` table. 
* Tests should be written for this functionality as well.

`createGivenAwayEvent` should accept fields:
| Field name  | Data Type |
| ------------- | ------------- |
| formerOwnerId  | Int (Required) |
| reason | String |
| animalId | Int (Required) |
| date | Date |

`updateGivenAwayEvent` should accept fields:
| Field name  | Data Type |
| ------------- | ------------- |
| id | Int (Required) |
| formerOwnerId  | Int |
| reason | String |
| animalId | Int |
| date | Date |

For example, we can look at organization GraphQL definition at https://github.com/pets-oss/pets-back/blob/main/src/schema/typeDefs/organization.graphql. The pull-request that introduced such mutations for organizations can be seen here #79 

### Usage example:

**Expected mutation**:
```graphql
mutation {
  createGivenAwayEvent (input: {
    formerOwnerId: 5,
    reason: "Leaving country"
    date: "2021-03-19",
    animalId: 4,
  }) {
    id,
    formerOwnerId,
    date,
    animalId,
    reason
  }
}
```
**Expected response** (returned id does not need to be exactly 1):
```JSON
{
  "data": {
    "createFoundEvent": {
      "id": 1,
      "formerOwnerId": 5,
      "reason": "Leaving country",
      "date": "2021-03-19",
      "animalId": 4,
    }
  }
}

```

**Expected mutation**:
```graphql
mutation {
  updateGivenAwayEvent (input: {
    id: 1,
    formerOwnerId: 6,
    reason: "Allergy"
    date: "2021-03-20",
    animalId: 5,
  }) {
    id,
    formerOwnerId,
    date,
    animalId,
    reason
  }
}
```
**Expected response**:
```JSON
{
  "data": {
    "createFoundEvent": {
      "id": 1,
      "formerOwnerId": 6,
      "reason": "Allergy",
      "date": "2021-03-20",
      "animalId": 5,
    }
  }
}

```

**Comment by pergaliuke** [comment]
I would like to work on this task. Assign me, please
