### ISSUE TITLE
Add mutations for former animal owner

### ISSUE THREAD

**Issue by ignasposka** [pets-oss/pets-back#131]
**Goal**

* Create a GraphQL mutation `createFormerAnimalOwner` that would create former animal owner data in the database.
* Create a GraphQL mutation `updateFormerAnimalOwner` that would update former animal owner data in the database by specific ID.

**Description**

* Former animal owners are being stored in `former_animal_owner` table. 
* Tests should be written for this functionality as well.

`createFormerAnimalOwner` should accept the following fields:
| Field name  | Data Type |
| ------------- | ------------- |
| name  | Name (Required) |
| name  | Surname (Required) |
| phone | Phone |

`updateFormerAnimalOwner` should accept the following fields:
| Field name  | Data Type |
| ------------- | ------------- |
| id | Int (Required)|
| name  | Name (Required) |
| surname  | Surname |
| phone | Phone |

Custom GraphQL scalars need to be introduced during this task:

* Name (String limited to 255 characters)
* Surname (String limited to 255 characters)
* Phone (String matching phone number pattern)

For example, we can look at organization GraphQL definition at https://github.com/pets-oss/pets-back/blob/main/src/schema/typeDefs/organization.graphql. The pull-request that introduced such mutations for organizations can be seen here #79 

### Usage example:

**Expected mutation**:
```graphql
mutation {
  createFormerAnimalOwner (input: {
    name: "Rimas",
    surname: "Petravičius",
    phone: "+37068745124"
  }) {
    id,
    name,
    surname,
    phone
  }
}
```

**Expected response** (id may differ):
```JSON
{
    "data": {
      "createFormerAnimalOwner": {
        "id": 1,
        "name": "Rimas",
        "surname": "Petravičius",
        "phone": "+37068745124"
      }
    }
}
```

**Expected mutation**:
```graphql
mutation {
  updateFormerAnimalOwner (input: {
    id: 1,
    name: "Rimas1",
    surname: "Petravičius1",
    phone: "+37068745125"
  }) {
    id,
    name,
    surname,
    phone
  }
}
```

**Expected response**:
```JSON
{
    "data": {
      "createFormerAnimalOwner": {
        "id": 1,
        "name": "Rimas1",
        "surname": "Petravičius1",
        "phone": "+37068745125"
      }
    }
}
```

**Comment by pergaliuke** [comment]
Assign me, please.
