### ISSUE TITLE
Animal update query expects microchip_id even when microchip data isn't being updated

### ISSUE THREAD

**Issue by JustasBelevicius** [pets-oss/pets-back#133]
microchip data is optional, this shouldn't trigger the microchip_id not null constraint.

**Comment by mantasimkus** [comment]
Does this bug still exist?

I have just tried executing the mutation below and it worked like a charm.

```
mutation {
  updateAnimal(input: {
    id: 1,
    name: "Reksas"
  }) {
    id,
    name
  }
}
```

**Comment by AzisK** [comment]
It seems that this bug was solved at some point

**Comment by AzisK** [comment]
Actually it was not solved and then reappeared. It was solved with this issue https://github.com/pets-oss/pets-back/issues/295 (and it's corresponding PR)
