### ISSUE TITLE
Create animal_favorite table to store user's favorite animals

### ISSUE THREAD

**Issue by AzisK** [pets-oss/pets-back#141]
**Goal**

Create animal_favorite table to store user's favorite animals

**Description**

One user can have multiple favorite animals and one animal can be favorite for several users (many to many relationship). Example:

user_id | animal_id
--------|----------
1|1
1|2
2|2

**Comment by mindra** [comment]
https://github.com/pets-oss/pets-back/pull/177 could be solution for this.

**Comment by rimantepomeckyte** [comment]
Please, add me as an assignee
