### ISSUE TITLE
Get rid of delete_time in organization table

### ISSUE THREAD

**Issue by AzisK** [pets-oss/pets-back#145]
**Goal** 

Get rid of delete_time in organization table

**Description**

This is a left-over from previous attempt to implement soft-deletes. However, it was abandoned for the MVP version. Make sure this change does not break any tests. Table DDL (data definition language):

```sql
CREATE TABLE organization (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(128),
    city VARCHAR(128),
    street_address VARCHAR(255),
    phone VARCHAR(64),
    mod_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    delete_time TIMESTAMP
);
```

**Comment by kostamir** [comment]
Got rid of delete_time. Fixed the code to pass all the tests.
