### ISSUE TITLE
Create a database table organization_task that would store organization tasks

### ISSUE THREAD

**Issue by AzisK** [pets-oss/pets-back#148]
**Goal**
Create a database table organization_task that would store organization tasks

**Description**
This table should build a base for this issue https://github.com/pets-oss/pets-back/issues/146. Therefore, the table definitely has to have such fields `id`, `title`, `description`, `is_done`. In order for us to have robust data, the table should have a foreign key of organization id.

**Comment by rimantepomeckyte** [comment]
Please add me as an assignee
