### ISSUE TITLE
Create a database query that would return current count of animals in organization

### ISSUE THREAD

**Issue by AzisK** [pets-oss/pets-back#149]
**Goal**
Create a database query that would return current count of animals

**Description**
Group this count by species and gender. Use the Lithuanian translations of species and gender ("lt" language). This information of current state will later be used to display the state of the organization or in reports. Please add this query in file `reports.sql` in the root of repository (can comment above it what is it about). For now we can look at the general state of organizations and later (when we have the GraphQL query ready) we can plug-in a WHERE filter to filter out the organization id. Example table below

species | gender | cnt
-|-|-
Šuo|Patelė|2
Katė|Patinas|1
Katė|Patelė|1
Šeškas|Patelė|1

**Comment by mantasimkus** [comment]
As there might be multiple organizations, should the query return:
a) general results among all organizations,
b) results in a specific organization only (using a hardcoded WHERE clause) or
c) results grouped by organization (it probably means storing some additional information in the table, say, organization name)?

**Comment by AzisK** [comment]
a) general results among all organizations
We can always amend the query and add a WHERE filter to filter the organization id

**Comment by mantasimkus** [comment]
I would like this issue to be assigned to me.
