### ISSUE TITLE
Normalize address in animal_event_found table

### ISSUE THREAD

**Issue by AzisK** [pets-oss/pets-back#151]
**Goal**
Normalize address in former_animal_owner table

**Description**
Suggestion to normalize is into street address and house number while house number is not a necessary field since sometimes it may be hard to determine next which house the animal was found. Current table structure:

```sql
CREATE TABLE animal_event_found (
    id SERIAL PRIMARY KEY,
    address VARCHAR(256),
    municipality_id INTEGER REFERENCES municipality(id) NOT NULL,
    date_time TIMESTAMP,
    animal_id INTEGER REFERENCES animal(id) ON DELETE CASCADE NOT NULL,
    comments TEXT
);
```

**Comment by pergaliuke** [comment]
I did it! :)

**Comment by JustasBelevicius** [comment]
@ieva1919
