### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by ignasposka** [pets-oss/pets-back#20]
Fix build warnings:
`npm WARN wcc_gis_backend@1.0.0 No repository field.
npm WARN wcc_gis_backend@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

**Comment by AzisK** [comment]
Also husky@4.3.6 is throwing a silent failure
