### ISSUE TITLE
Add mutations for general event

### ISSUE THREAD

**Issue by ignasposka** [pets-oss/pets-back#216]
* Create a GraphQL mutation `createGeneralEvent` that would create found event data in the database.
* Create a GraphQL mutation `updateGeneralEvent` that would update found event data in the database by specific ID.
* Create a GraphQL mutation `deleteGeneralEvent` that would delete found event data in the database by specific ID.

**Description**

* Given away events are being stored in `animal_event_general` table. 
* `dateTime` should be set to current if not present
* Tests should be written for this functionality as well.

`createGeneralEvent` should accept fields:
| Field name  | Data Type |
| ------------- | ------------- |
| animalId  | Int (Required) |
| type | String |
| expenses | Float (Required) |
| dateTime | String |
| comments | String |

`updateGeneralEvent` should accept fields:
| Field name  | Data Type |
| ------------- | ------------- |
| id | Int (Required) |
| animalId  | Int |
| type | String |
| expenses | Float |
| dateTime | String |
| comments | String |

For example, we can look at organization GraphQL definition at https://github.com/pets-oss/pets-back/blob/main/src/schema/typeDefs/organization.graphql. The pull-request that introduced such mutations for organizations can be seen here #79

**Comment by AzisK** [comment]
Deprecating this issue, there is no need
