### ISSUE TITLE
Error output is not being shown in docker logs

### ISSUE THREAD

**Issue by ignasposka** [pets-oss/pets-back#240]
How to reproduce:
1. Go to any `.graphql` file and add duplicate field for any type
2. Go to docker log and see `[nodemon] app crashed - waiting for file changes before starting...`

Expected output in docker log is: `Error: Field "FoundEvent.author" can only be defined once.`

**Comment by pergaliuke** [comment]
> How to reproduce:
> 
> 1. Go to any `.graphql` file and add duplicate field for any type
> 2. Go to docker log and see `[nodemon] app crashed - waiting for file changes before starting...`
> 
> Expected output in docker log is: `Error: Field "FoundEvent.author" can only be defined once.`

Is this is still an issue? I can not reproduce:
![image](https://user-images.githubusercontent.com/48152843/120179207-f32dd880-c212-11eb-990c-8bec7700af27.png)

By default, Apollo Server omits the exception.stacktrace field if the NODE_ENV environment variable is set to either production or test.

**Comment by AzisK** [comment]
I also get this error although I don't have NODE_ENV anywhere

**Comment by AzisK** [comment]
Closing unless someone can confirm this issue
