### ISSUE TITLE
Create `eventGroups` and `eventTypes` query

### ISSUE THREAD

**Issue by JBK91** [pets-oss/pets-back#243]
Create `eventGroups` query which returns all groups from `event_group` enum.

Create `eventTypes` query.
This query should have argument `group` of `enum_group` enum and returns all types which belongs to given group.

Both queries should return array of objects in format: 
`{ 
  id: id,
  value: value
}`

For example: 
`[
{
  id: 'Medical',
  value: 'Medical'
}, 
{
  id: 'General',
  value: 'General'
}
]`

All data should be saved in static object and resolvers should use that object.

Event types and their groups are:

**Group Medical:**
'Medication', 
'Prophylaxis',
 'Surgery', 
'GenderElimination', 
'Inspection'

**Group General:**
'GivenAway', 
'Found',
'CheckIn',
'CheckOut',
'Died',
'TemporaryCare',
'Microchipped',
'LocationChange'

**Comment by AzisK** [comment]
AFAIK there is a discussion whether this is needed. The translation might be done in front-end.

**Comment by AzisK** [comment]
Closing it since seems like we will not need it
