### ISSUE TITLE
Add commit hook to run eslint.

### ISSUE THREAD

**Issue by ignasposka** [pets-oss/pets-back#80]

**Comment by JustasBelevicius** [comment]
Already done on every PR, can we close this @ignasposka?
https://github.com/pets-oss/pets-back/blob/e4407b9ca4a1c091197d21b39063523f635ca993/.github/workflows/pull-request.yml#L44-L45
https://github.com/pets-oss/pets-back/blob/e4407b9ca4a1c091197d21b39063523f635ca993/package.json#L18

**Comment by ignasposka** [comment]
I wanted that commit hook would prevent commit locally in case of eslint errors.
