### ISSUE TITLE
Allow animals to be requested by a list of ids

### ISSUE THREAD

**Issue by JustasBelevicius** [pets-oss/pets-back#94]
**Goal**

Create an API that 

-> when provided with a list of animal ids

<- would return a list of animal entries 

**Description**

In certain use cases Front-end needs to get animal entries for a list of animal ids in a single request. Please implement such feature. Example GraphQL query and response should look like below. Please also write automatic tests that would capture whether this feature is working as expected.

It is already possible to get all animal entries with such query:

```graphql
{
    animals {
        name
    }
}
```

**Expected behaviour**

A. Such input

```graphql
{
    animals(ids: [1,2,3]) {
        name
  }
}
```

Should expect fields of 3 animals, e.g.

```json
{
  "data": {
    "animals": [
      {
        "name": "Haskelis"
      },
      {
        "name": "Jupyteris"
      },
      {
        "name": "Pitoncas"
      }
    ]
  }
}
```

B. Input without any animal ids specified

```graphql
{
    animals() {
        name
  }
}
```

Should return all animal entries, e.g.:

```json
{
  "data": {
    "animals": [
      {
        "name": "Haskelis"
      },
      {
        "name": "Jupyteris"
      },
      {
        "name": "Pitoncas"
      },
      {
        "name": "Javainis"
      },
      {
        "name": "Murkė"
      },
      {
        "name": "Grikis"
      }
    ]
  }
}
```

**Comment by pergaliuke** [comment]
Assign me, please.
